<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
   	<li><a href="<?php echo $listUrl;?>">运营</a></li>
	<li><a href="<?php echo $settingUrl;?>">消息设置</a></li>
	<li class="current"><a href="javascript:;">消息明细</a></li>
	</ul>
</div>

<div class="h_a">消息 <span style="font-weight:700;">"<?php echo $msgTitle;?>"</span> 明细：</div>
<form method="post" action="<?php echo $detailUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
<input name="id" value="<?php echo $id;?>" type="hidden" />
<div class="h_a">
	<span>&nbsp;&nbsp;&nbsp;&nbsp;共 <?php echo $total;?> 条结果</span>
</div>
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td><input type="checkbox" onclick="checkAll('.checkbox')"></td>
			<td width="100">头像</td>
			<td >昵称</td>
			<td>账号</td>
			<td>uuid</td>
			<td>接受时间</td>				
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td><input class="checkbox" name="ids[]" value="<?php echo $value['id'];?>" type="checkbox"></td>
			<td>
			<?php if(!empty($value['pic'])) {?>
			<img src="<?php echo $attachPath. $value['pic'];?>" title="" width="100"/>
			<?php } ?>
			</td>
			<td><?php echo $value['nick'];?></td>
			<td><?php echo $value['account'];?></td>
			<td><?php echo $value['uuid'];?></td>
			<td><?php echo $value['time'];?></td>			
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<?php echo $this->render("layout/footer.phtml");?>