<?php echo $this->render("layout/header.phtml");?>
<div class="nav">
	<ul class="cc">
   	<li><a href="<?php echo $listUrl;?>">运营消息</a></li>
	<li><a href="<?php echo $settingUrl;?>?type=100">消息设置</a></li>
	<li class="current"><a href="javascript:;">消息明细</a></li>
	</ul>
</div>

<div class="h_a">消息 <span style="font-weight:700;"><?php echo $type == 103 ? "奖励提示" : "A券过期";?></span> 累计： <span style="font-weight:700;"><?php echo $total;?></span>条 &nbsp;&nbsp;&nbsp;&nbsp;今日: <span style="font-weight:700;"><?php echo $currTotal;?></span></div>
<div class="h_a"><a href="<?php echo $sysMsgUrl;?>">返回系统消息</a></div>
<form method="post" action="<?php echo $detailUrl;?>" id="addFrom">
<input name="token" value="<?php echo $token;?>" type="hidden" />
</form>
<div class="table_list">
	<table width="100%">
		<tr class="hd">
			<td width="100">头像</td>
			<td >昵称</td>
			<td>账号</td>
			<td>生成时间</td>	
			<td>状态</td>	
			<td>uuid</td>
			<td>接受时间</td>			
			<td>内容</td>	
		</tr>
<?php foreach($result as $key => $value) {?>
		<tr class="ct">
			<td>
			<?php if(!empty($usersInfo[$value['id']]['avatar'])) {?>
			<img src="<?php echo $attachPath.$usersInfo[$value['id']]['avatar'];?>" title="" width="100"/>
			<?php } ?>
			</td>
			<td><?php echo $usersInfo[$value['id']]['nickname'];?></td>
			<td><?php echo $usersInfo[$value['id']]['uname'];?></td>
			<td><?php echo date('Y-m-d H:i:s', $value['create_time']);?></td>
			<td><?php echo $usersInfo[$value['id']]['read_time'] ? '已接收' : '未接收';?></td>
			<td><?php echo $usersInfo[$value['id']]['uid'];?></td>
			<td><?php echo $usersInfo[$value['id']]['read_time'] ? date('Y-m-d H:i:s', $usersInfo[$value['id']]['read_time']) : '';?></td>		
			<td><?php echo $usersInfo[$value['id']]['content'];?></td>	
		</tr>
<?php } ?>
	</table>
</div>
<div class="mr10 cc">
<?php echo $pager;?>
</div>
<script src="<?php echo $staticPath;?>/js/common/jquery-ui-timepicker.js"></script>
<script type="text/javascript">
function _export_() {
	window.location.href = "<?php echo $detailUrl.'?'.http_build_query($searchParam);?>&export=1";
	return false;
}
//表单数据提交
$(document).ready(function(){
	
})
</script>
<?php echo $this->render("layout/footer.phtml");?>