<?php
echo <<<HTML
<!doctype html>
<html>
<meta charset="utf-8">
<title>管理系统</title>
<script src="$staticPath/js/common/jquery.js?v=$version"></script>
<script src="$staticPath/js/common/jquery-ui.min.js?v=$version"></script>
<script src="$staticPath/js/common/jquery.form.js?v=$version"></script>
<script src="$staticPath/js/common/common.js?v=$version"></script>
<script>
var token = "$token";
var baseurl = "$adminroot";
</script>
<link href="$staticPath/css/style.css?v=$version" rel="stylesheet" />
<link rel="stylesheet" href="$staticPath/css/jquery-ui.css?v=$version" />
<link href="$staticPath/css/star/star.source.css?v=$version" rel="stylesheet" />
<style>
.hide { display: none; }
.red { color: #f00; }
a { cursor: pointer; }
</style>
</head>
<body>
<div class="wrap">
HTML;
?>
