<?php
echo <<<HTML
<!doctype html>
<html>
<meta charset="utf-8">
<title>管理系统</title>
<script src="{$staticPath}/game/assets/js/jquery-1.11.3.min.js"></script>
<script src="{$staticPath}/game/assets/js/jquery-ui.1.11.4.js"></script>
<script src="{$staticPath}/game/assets/js/jquery.form.js"></script>
<script src="{$staticPath}/game/assets/js/common/common.js?v=$version"></script>
<script>
var token = "$token";
var baseurl = "$adminroot";
</script>
<link href="$staticPath/game/assets/css/style.css?v=$version" rel="stylesheet" />
<link href="{$staticPath}/game/assets/css/jquery-ui-1.3.css?v=$version" rel="stylesheet"/>
<link href="$staticPath/game/assets/css/star/star.source.css?v=$version" rel="stylesheet" />
<style>
.hide { display: none; }
.red { color: #f00; }
a { cursor: pointer; }
</style>
</head>
<body>
<div class="wrap">
HTML;
?>